INCLUDE memory-k210.x

REGION_ALIAS("REGION_TEXT", SRAM_NOCACHE);
REGION_ALIAS("REGION_RODATA", SRAM_NOCACHE);
REGION_ALIAS("REGION_DATA", SRAM_NOCACHE);
REGION_ALIAS("REGION_BSS", SRAM_NOCACHE);
REGION_ALIAS("REGION_HEAP", SRAM_NOCACHE);
REGION_ALIAS("REGION_STACK", SRAM_NOCACHE);
